export enum StepEnum {
    GET_CLIENT_ID = 0,
    APPROVE_CLIENT_PRESONAL_DETAILS = 1,
    CLIENT_QUESTIONNAIRE_1 = 2,
    CLIENT_QUESTIONNAIRE_2 = 3,
    CLIENT_QUESTIONNAIRE_RESULT = 4,
    CLIENT_QUESTIONNAIRE_REPORTS = 5,
}